// Tron message-signing KAT generator + WalletCore cross-check (run manually):
//
//   cargo test -p ledger-tron-core --test kat_gen -- --ignored --nocapture
//
// Emits the canonical Tron TIP-191 vector (frozen into
// test-vectors/tron-message-signing-kat.json, asserted by the Rust core + iOS
// + Android). It ALSO asserts that tron_sign_message reproduces Trust Wallet
// Core's published TronMessageSigner test vector byte-for-byte, so the shared
// Rust core is independently validated against WalletCore (which the apps use
// to derive keys). Tron is mainnet-only.

use bitcoin::bip32::{DerivationPath, Xpriv};
use bitcoin::secp256k1::Secp256k1;
use bitcoin::Network;
use ledger_tron_core::tron_sign_message;
use std::str::FromStr;

// Standard BIP-39 test mnemonic seed (empty passphrase) — same as the BTC KAT.
const TEST_MNEMONIC: &str = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
const TEST_SEED_HEX: &str = "5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc19a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4";
const TRON_PATH: &str = "m/44'/195'/0'/0/0";
const TRON_MESSAGE: &str = "Maknoon TIP-191 KAT v1";

// Trust Wallet Core's TronMessageSigner test vector (tests/chains/Tron).
const WC_KEY_HEX: &str = "75065f100e38d3f3b4c5c4235834ba8216de62272a4f03532c44b31a5734360a";
const WC_MESSAGE: &str = "Hello World";
const WC_EXPECTED_SIG: &str = "bc0753c070cc55693097df11bc11e1a7c4bd5e1a40b9dc94c75568e59bcc9d6b50a7873ef25b469e494490a54de37327b4bc7fc825c81a377b555e34fb7261ba1c";

fn secret_at(path: &str) -> [u8; 32] {
    let secp = Secp256k1::new();
    let seed = hex::decode(TEST_SEED_HEX).unwrap();
    let master = Xpriv::new_master(Network::Bitcoin, &seed).unwrap();
    let dp = DerivationPath::from_str(path).unwrap();
    master.derive_priv(&secp, &dp).unwrap().private_key.secret_bytes()
}

#[test]
#[ignore]
fn generate_tron_kat_vector() {
    // 1. Independent cross-check against Trust Wallet Core's known vector.
    let wc_key = hex::decode(WC_KEY_HEX).unwrap();
    let wc = tron_sign_message(wc_key, WC_MESSAGE.to_string()).unwrap();
    let wc_sig_no0x = wc.signature.trim_start_matches("0x");
    assert_eq!(
        wc_sig_no0x, WC_EXPECTED_SIG,
        "tron_sign_message must reproduce WalletCore TronMessageSigner byte-for-byte"
    );

    // 2. Canonical vector from the standard test mnemonic.
    let sk = secret_at(TRON_PATH);
    let signed = tron_sign_message(sk.to_vec(), TRON_MESSAGE.to_string()).unwrap();

    let corpus = serde_json::json!({
        "_comment": "Canonical Tron TIP-191 KAT. Generated by ledger-tron-core/tests/kat_gen.rs (cross-checked against Trust Wallet Core's TronMessageSigner vector). Asserted by the Rust core, iOS, and Android. Mainnet only.",
        "mnemonic": TEST_MNEMONIC,
        "seedHex": TEST_SEED_HEX,
        "tron": {
            "path": TRON_PATH,
            "secretKeyHex": hex::encode(sk),
            "message": TRON_MESSAGE,
            "expectedAddress": signed.address,
            "expectedSignature": signed.signature
        }
    });
    println!("KAT_JSON_BEGIN");
    println!("{}", serde_json::to_string_pretty(&corpus).unwrap());
    println!("KAT_JSON_END");
}
